### ISSUE TITLE
关于fdm

### ISSUE THREAD

**Issue by LamJet** [LGA1150/SYSUv6-hosts#1]
请问一下fdm容易崩吗，我用来下油管视频总是崩掉的。。。[笑哭]

**Comment by LGA1150** [comment]
目前的确有这个BUG，多试几次就好了，一旦连接上，速度是非常快的。
![image](https://cloud.githubusercontent.com/assets/9155358/11767349/b2d3ca90-a1e5-11e5-93c2-cb6a9e44cfc9.png)

**Comment by LamJet** [comment]
嗯，是的，多连几次就好了，还以为是自己的问题。。。还有，想请问一下，如果以后ipv6也开始墙了，或者ipv6也普及了，速度该怎么办？[叹气]

**Comment by LGA1150** [comment]
目前 CNGI-BJIX 到 HKIX 有 10Gbps 的带宽，还是够用的
P.S. : 在 GitHub 上使用 Emoji 表情： http://www.emoji-cheat-sheet.com

**Comment by LamJet** [comment]
thx :smile: 对了，上次说的就是dns域名劫持。。。那要附加的那个加在哪里？另外加了那个是说用ipv6的dns吗?

**Comment by LGA1150** [comment]
直接贴在hosts里
不需要修改DNS

**Comment by LamJet** [comment]
ok,thx
