### ISSUE TITLE
如果可以 能不能将v4和v6分出来？

### ISSUE THREAD

**Issue by Myer921** [LGA1150/SYSUv6-hosts#2]
如果可以 能不能将v4和v6分出来？
因为有一部分去广hosts会本hosts冲突
然后我对v4的使用要求并不大 对v6比较大 所以麻烦下次搞得时候单独做个版本 谢谢

**Comment by Myer921** [comment]
同时在这个lssues申请一下授权
我可以在一定范围内搭建Dns服务并使用本hosts吗？ （范围：团队 用户数量：不超过20人
谢谢

**Comment by LGA1150** [comment]
不理解把v4和v6分开跟去广告的关系
如果你的意思是本hosts中有一些广告域名，可自行注释掉
（当然考虑到大部分人在家没v6环境，我会做一个v4版本，不过仅限于Google）

你可以使用本hosts做DNS
