### ISSUE TITLE
GCN 域名解析变动

### ISSUE THREAD

**Issue by aofall** [LGA1150/SYSUv6-hosts#3]
中国大陆地区的AAAA记录默认解析到澳大利亚？
以下是项目中还没有的域名
g.cn
pack.google.cn
gstatic.cn
www.gstatic.cn

**Comment by LGA1150** [comment]
不要被“IP注册地”迷惑
亚太地区的IP段 `2404:6800::/32` 注册地都是澳大利亚
CN域名都解析到台湾的 `2404:6800:4008::/40`

**Comment by aofall** [comment]
知道了。
IPv4也被解析到台湾了，不是北京服务器

**Comment by LGA1150** [comment]
我用运营商的DNS和CNNIC DNS，除了dl外都正常

**Comment by aofall** [comment]
😂其实我只是想说cn的A记录解析到台湾去了（移动的默认DNS），顺便补充缺少的域名
在ipip.net的DNS工具也有发现少部分的移动、教育网被解析到台湾

**Comment by aofall** [comment]
除了dl，其余的A记录恢复了
